apiVersion: v1
kind: Pod
metadata:
  name: copy-helper
spec:
  containers:
    - name: copy-helper
      image: busybox
      command: ["sleep", "3600"]
      volumeMounts:
        - name: model-store
          mountPath: /mnt/models
  volumes:
    - name: model-store
      persistentVolumeClaim:
        claimName: model-store
